#!/bin/bash
#!/bin/bash
#SBATCH -J kmeans                   # task name
#SBATCH -o kmeans.out               # redirect output to test.out
#SBATCH -N 4                    # nodes
#SBATCH --tasks-per-node 2
#SBATCH -t 1:00:00                # time for a task

# 设置运行环境

module load openmpi/gnu/2.1.1

mpirun -np 8 ./kmeans 100000 4